# Generated by Django 5.2 on 2025-05-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
