# Generated by Django 5.2 on 2025-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_cart_id_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
