# Generated by Django 5.2 on 2025-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_order_phone_number_alter_order_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique numeric identifier for the cart",
                max_length=50,
                unique=True,
            ),
        ),
    ]
