# Generated by Django 5.2 on 2025-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique identifier for the cart",
                max_length=50,
                unique=True,
            ),
        ),
    ]
