# Generated by Django 5.2 on 2025-05-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
