# Generated by Django 5.2 on 2025-05-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Enter the category name (max 50 characters)",
                        max_length=50,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from category name",
                        max_length=100,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description (max 255 characters)",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a category image (optional)",
                        upload_to="categories/%Y/%m/%d/",
                        verbose_name="Category Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["category_name"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories__slug_9b1a28_idx")
                ],
            },
        ),
    ]
