# Generated by Django 5.2 on 2025-05-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Enter product name (max 200 characters)",
                        max_length=200,
                        unique=True,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        help_text="Auto-generated from product name",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Description"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Store in cents for precise calculations",
                        verbose_name="Price (in cents)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        help_text="Upload product image (optional)",
                        upload_to="photos/products/%Y/%m/%d/",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this product",
                        verbose_name="Available",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="categories.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_date"],
            },
        ),
    ]
