# Generated by Django 5.2 on 2025-05-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/products/%Y/%m/%d/",
                verbose_name="Product Image",
            ),
        ),
    ]
