# Generated by Django 5.2 on 2025-05-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
