# Generated by Django 5.2 on 2025-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Enter product price (e.g., 179.99)",
                max_digits=10,
                verbose_name="Price ($)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Auto-generated from product name",
                max_length=250,
                unique=True,
            ),
        ),
    ]
