# Generated by Django 5.2 on 2025-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_price_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="num_purchases",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Purchases"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="num_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Views"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="num_wishlist",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Wishlist Adds"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="popularity_score",
            field=models.FloatField(default=0.0, verbose_name="Popularity Score"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price ($)"
            ),
        ),
    ]
