# Generated by Django 5.2 on 2025-05-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
        ("store", "0005_product_num_purchases_product_num_views_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=5,
                verbose_name="Rating (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
