# Generated by Django 5.2 on 2025-05-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_alter_rating_options_remove_rating_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
    ]
