# Generated by Django 5.2 on 2025-06-01 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status_payment"),
        ("store", "0005_product_num_purchases_product_num_views_and_more"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("cart", "Add to Cart"),
                            ("wishlist", "Add to Wishlist"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction Event",
                "verbose_name_plural": "Interaction Events",
            },
        ),
        migrations.DeleteModel(
            name="ProductView",
        ),
        migrations.AddIndex(
            model_name="interactionevent",
            index=models.Index(
                fields=["user", "product", "interaction_type", "timestamp"],
                name="tracking_in_user_id_d1ff3f_idx",
            ),
        ),
    ]
